export const SEARCH_MOVIE_PENDING = "SEARCH_MOVIE_PENDING";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_FAILED = "SEARCH_MOVIE_FAILED";

export const GET_SEARCH_INPUT = "GET_SEARCH_INPUT";

export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_RENDER_DETAIL = "GET_RENDER_DETAIL";

export const REQUEST_DETAIL_PENDING = "REQUEST_DETAIL_PENDING";
export const REQUEST_DETAIL_SUCCESS = "REQUEST_DETAIL_SUCCESS";
export const REQUEST_DETAIL_FAILED = "REQUEST_DETAIL_FAILED";

export const FETCH_MOVIES_PENDING = "FETCH_MOVIES_PENDING";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";

export const FETCH_MOVIES_BY_GENRE = "FETCH_MOVIES_BY_GENRE";
export const FETCH_GENRE = "FETCH_GENRE";

export const FETCH_RELATED_MOVIES = "FETCH_RELATED_MOVIES";
export const FETCH_MOVIE_CAST = "FETCH_CREDITS_MOVIES";
export const CLEANING_MOVIE_STATE = "CLEANING_MOVIE_STATE";
export const GET_ACTOR_PROFILE = "GET_ACTOR_PROFILE";
export const GET_ACTOR_CREDIT_MOVIES = "GET_ACTOR_CREDIT_MOVIES";

export const API_KEY = "bcc62cd0ae2694d5d52747a14d34ecac";
export const DEFAULT_URL = "https://api.themoviedb.org/3";
export const CORS_PROXY = "https://cors.io/?";
